import { TopologyData, NetworkNode, NetworkLink, DeviceRole, VxlanTunnel } from '@/types/topology';

// Spine-Leaf 아키텍처 기반 모킹 데이터 생성 함수
export function generateMockTopologyData(): TopologyData {
  const nodes: NetworkNode[] = [
    // Spine 스위치 (최상위 계층) - VTEP 지원
    {
      id: 'spine-1',
      type: 'switch',
      label: 'Leaf 4-1',
      status: 'active',
      role: 'spine' as DeviceRole,
      ip: '10.0.116.51',
      mac: 'AA:BB:CC:DD:EE:01',
      vxlanVni: 5000, // VxLAN VNI
      vtepIp: '10.0.116.51', // VTEP IP
      bandwidth: 40000,
      bandwidthLabel: '40G',
      layer: 1,
      position: { x: 200, y: 100 },
    },
    {
      id: 'spine-2',
      type: 'switch',
      label: 'Leaf 4-2',
      status: 'active',
      role: 'spine' as DeviceRole,
      ip: '10.0.116.52',
      mac: 'AA:BB:CC:DD:EE:02',
      vxlanVni: 5000, // VxLAN VNI
      vtepIp: '10.0.116.52', // VTEP IP
      bandwidth: 40000,
      bandwidthLabel: '40G',
      layer: 1,
      position: { x: 500, y: 100 },
    },
    {
      id: 'spine-3',
      type: 'switch',
      label: 'Leaf 4-3',
      status: 'active',
      role: 'spine' as DeviceRole,
      ip: '10.0.116.53',
      mac: 'AA:BB:CC:DD:EE:03',
      vxlanVni: 5000, // VxLAN VNI
      vtepIp: '10.0.116.53', // VTEP IP
      bandwidth: 40000,
      bandwidthLabel: '40G',
      layer: 1,
      position: { x: 800, y: 100 },
    },
    // Leaf 스위치 (중간 계층)
    {
      id: 'leaf-1',
      type: 'switch',
      label: 'Leaf3',
      status: 'active',
      role: 'leaf' as DeviceRole,
      ip: '10.0.116.61',
      mac: 'AA:BB:CC:DD:EE:11',
      vlan: 100,
      vxlanVni: 5100, // VxLAN VNI
      vtepIp: '10.0.116.61', // VTEP IP
      bandwidth: 10000,
      bandwidthLabel: '10G',
      layer: 2,
      position: { x: 100, y: 250 },
    },
    {
      id: 'leaf-2',
      type: 'switch',
      label: 'Spine2',
      status: 'error',
      severity: 'critical',
      role: 'leaf' as DeviceRole,
      ip: '10.0.116.54',
      mac: 'AA:BB:CC:DD:EE:12',
      vlan: 100,
      bandwidth: 10000,
      bandwidthLabel: '10G',
      layer: 2,
      position: { x: 250, y: 250 },
    },
    {
      id: 'leaf-3',
      type: 'switch',
      label: 'Spine1',
      status: 'active',
      role: 'leaf' as DeviceRole,
      ip: '10.0.116.52',
      mac: 'AA:BB:CC:DD:EE:13',
      vlan: 200,
      vxlanVni: 5200, // VxLAN VNI
      vtepIp: '10.0.116.52', // VTEP IP
      bandwidth: 10000,
      bandwidthLabel: '10G',
      layer: 2,
      position: { x: 400, y: 250 },
    },
    {
      id: 'leaf-4',
      type: 'switch',
      label: 'Leaf4-POE',
      status: 'warning',
      severity: 'minor',
      role: 'leaf' as DeviceRole,
      ip: '10.0.116.56',
      mac: 'AA:BB:CC:DD:EE:14',
      vlan: 200,
      vxlanVni: 5200, // VxLAN VNI
      vtepIp: '10.0.116.56', // VTEP IP
      bandwidth: 10000,
      bandwidthLabel: '10G',
      layer: 2,
      position: { x: 550, y: 250 },
    },
    {
      id: 'leaf-5',
      type: 'switch',
      label: 'Backbone1',
      status: 'active',
      role: 'leaf' as DeviceRole,
      ip: '10.0.116.51',
      mac: 'AA:BB:CC:DD:EE:15',
      vlan: 300,
      bandwidth: 10000,
      bandwidthLabel: '10G',
      layer: 2,
      position: { x: 700, y: 250 },
    },
    {
      id: 'leaf-6',
      type: 'switch',
      label: 'Leaf1',
      status: 'active',
      role: 'leaf' as DeviceRole,
      ip: '10.0.116.61',
      mac: 'AA:BB:CC:DD:EE:16',
      vlan: 300,
      bandwidth: 10000,
      bandwidthLabel: '10G',
      layer: 2,
      position: { x: 850, y: 250 },
    },
    // 그룹 노드 (하위 계층) - 첫 번째 열
    {
      id: 'group-1-1',
      type: 'group',
      label: 'GROUP',
      status: 'active',
      ip: '192.168.10.1',
      vlan: 100,
      layer: 3,
      position: { x: 50, y: 400 },
    },
    {
      id: 'group-1-2',
      type: 'group',
      label: 'GROUP',
      status: 'active',
      ip: '192.168.10.2',
      vlan: 100,
      layer: 3,
      position: { x: 150, y: 400 },
    },
    {
      id: 'group-2-1',
      type: 'group',
      label: 'GROUP',
      status: 'error',
      severity: 'critical',
      ip: '192.168.11.1',
      vlan: 100,
      layer: 3,
      position: { x: 200, y: 400 },
    },
    {
      id: 'group-2-2',
      type: 'group',
      label: 'GROUP',
      status: 'active',
      ip: '192.168.11.2',
      vlan: 100,
      layer: 3,
      position: { x: 300, y: 400 },
    },
    {
      id: 'group-3-1',
      type: 'group',
      label: 'GROUP',
      status: 'active',
      ip: '192.168.12.1',
      vlan: 200,
      layer: 3,
      position: { x: 350, y: 400 },
    },
    {
      id: 'group-3-2',
      type: 'group',
      label: 'GROUP',
      status: 'active',
      ip: '192.168.12.2',
      vlan: 200,
      layer: 3,
      position: { x: 450, y: 400 },
    },
    {
      id: 'group-4-1',
      type: 'group',
      label: 'GROUP',
      status: 'warning',
      severity: 'minor',
      ip: '192.168.13.1',
      vlan: 200,
      layer: 3,
      position: { x: 500, y: 400 },
    },
    {
      id: 'group-4-2',
      type: 'group',
      label: 'GROUP',
      status: 'active',
      ip: '192.168.13.2',
      vlan: 200,
      layer: 3,
      position: { x: 600, y: 400 },
    },
    {
      id: 'group-5-1',
      type: 'group',
      label: 'GROUP',
      status: 'active',
      ip: '192.168.14.1',
      vlan: 300,
      layer: 3,
      position: { x: 650, y: 400 },
    },
    {
      id: 'group-5-2',
      type: 'group',
      label: 'GROUP',
      status: 'active',
      ip: '192.168.14.2',
      vlan: 300,
      layer: 3,
      position: { x: 750, y: 400 },
    },
    {
      id: 'group-6-1',
      type: 'group',
      label: 'GROUP',
      status: 'active',
      ip: '192.168.15.1',
      vlan: 300,
      layer: 3,
      position: { x: 800, y: 400 },
    },
    {
      id: 'group-6-2',
      type: 'group',
      label: 'GROUP',
      status: 'active',
      ip: '192.168.15.2',
      vlan: 300,
      layer: 3,
      position: { x: 900, y: 400 },
    },
    // 최하위 그룹 노드
    {
      id: 'group-1-1-1',
      type: 'group',
      label: 'GROUP',
      status: 'active',
      vlan: 100,
      layer: 4,
      position: { x: 50, y: 550 },
    },
    {
      id: 'group-1-2-1',
      type: 'group',
      label: 'GROUP',
      status: 'active',
      vlan: 100,
      layer: 4,
      position: { x: 150, y: 550 },
    },
    {
      id: 'group-2-1-1',
      type: 'group',
      label: 'GROUP',
      status: 'inactive',
      vlan: 100,
      layer: 4,
      position: { x: 200, y: 550 },
    },
    {
      id: 'group-2-2-1',
      type: 'group',
      label: 'GROUP',
      status: 'active',
      vlan: 100,
      layer: 4,
      position: { x: 300, y: 550 },
    },
    {
      id: 'group-3-1-1',
      type: 'group',
      label: 'GROUP',
      status: 'active',
      vlan: 200,
      layer: 4,
      position: { x: 350, y: 550 },
    },
    {
      id: 'group-3-2-1',
      type: 'group',
      label: 'GROUP',
      status: 'active',
      vlan: 200,
      layer: 4,
      position: { x: 450, y: 550 },
    },
    {
      id: 'group-4-1-1',
      type: 'group',
      label: 'GROUP',
      status: 'active',
      vlan: 200,
      layer: 4,
      position: { x: 500, y: 550 },
    },
    {
      id: 'group-4-2-1',
      type: 'group',
      label: 'GROUP',
      status: 'active',
      vlan: 200,
      layer: 4,
      position: { x: 600, y: 550 },
    },
    {
      id: 'group-5-1-1',
      type: 'group',
      label: 'GROUP',
      status: 'active',
      vlan: 300,
      layer: 4,
      position: { x: 650, y: 550 },
    },
    {
      id: 'group-5-2-1',
      type: 'group',
      label: 'GROUP',
      status: 'active',
      vlan: 300,
      layer: 4,
      position: { x: 750, y: 550 },
    },
    {
      id: 'group-6-1-1',
      type: 'group',
      label: 'GROUP',
      status: 'active',
      vlan: 300,
      layer: 4,
      position: { x: 800, y: 550 },
    },
    {
      id: 'group-6-2-1',
      type: 'group',
      label: 'GROUP',
      status: 'active',
      vlan: 300,
      layer: 4,
      position: { x: 900, y: 550 },
    },
  ];

  const links: NetworkLink[] = [
    // Spine 간 연결 (40G) - VxLAN 터널 사용
    {
      id: 'link-spine-1-2',
      source: 'spine-1',
      target: 'spine-2',
      bandwidth: 40000,
      utilization: 35,
      status: 'active',
      type: 'vxlan', // VxLAN 터널
      isVxlanTunnel: true,
      vxlanVni: 5000,
      latency: 0.3,
      packetLoss: 0,
    },
    {
      id: 'link-spine-2-3',
      source: 'spine-2',
      target: 'spine-3',
      bandwidth: 40000,
      utilization: 42,
      status: 'active',
      type: 'vxlan', // VxLAN 터널
      isVxlanTunnel: true,
      vxlanVni: 5000,
      latency: 0.3,
      packetLoss: 0,
    },
    // Spine-Leaf 연결 (40G)
    {
      id: 'link-spine1-leaf1',
      source: 'spine-1',
      target: 'leaf-1',
      bandwidth: 40000,
      utilization: 28,
      status: 'active',
      type: 'optical',
      latency: 0.5,
      packetLoss: 0,
    },
    {
      id: 'link-spine1-leaf2',
      source: 'spine-1',
      target: 'leaf-2',
      bandwidth: 40000,
      utilization: 0,
      status: 'down',
      type: 'optical',
      latency: 999,
      packetLoss: 100,
    },
    {
      id: 'link-spine2-leaf2',
      source: 'spine-2',
      target: 'leaf-2',
      bandwidth: 40000,
      utilization: 0,
      status: 'down',
      type: 'optical',
      latency: 999,
      packetLoss: 100,
    },
    {
      id: 'link-spine2-leaf3',
      source: 'spine-2',
      target: 'leaf-3',
      bandwidth: 40000,
      utilization: 55,
      status: 'active',
      type: 'optical',
      latency: 0.5,
      packetLoss: 0,
    },
    {
      id: 'link-spine2-leaf4',
      source: 'spine-2',
      target: 'leaf-4',
      bandwidth: 40000,
      utilization: 72,
      status: 'congested',
      type: 'optical',
      latency: 1.2,
      packetLoss: 0.05,
    },
    {
      id: 'link-spine3-leaf4',
      source: 'spine-3',
      target: 'leaf-4',
      bandwidth: 40000,
      utilization: 68,
      status: 'congested',
      type: 'optical',
      latency: 1.0,
      packetLoss: 0.03,
    },
    {
      id: 'link-spine3-leaf5',
      source: 'spine-3',
      target: 'leaf-5',
      bandwidth: 40000,
      utilization: 45,
      status: 'active',
      type: 'optical',
      latency: 0.5,
      packetLoss: 0,
    },
    {
      id: 'link-spine3-leaf6',
      source: 'spine-3',
      target: 'leaf-6',
      bandwidth: 40000,
      utilization: 38,
      status: 'active',
      type: 'optical',
      latency: 0.5,
      packetLoss: 0,
    },
    // Leaf-Group 연결 (10G)
    {
      id: 'link-leaf1-g1-1',
      source: 'leaf-1',
      target: 'group-1-1',
      bandwidth: 10000,
      utilization: 45,
      status: 'active',
      type: 'ethernet',
      latency: 1.0,
      packetLoss: 0,
    },
    {
      id: 'link-leaf1-g1-2',
      source: 'leaf-1',
      target: 'group-1-2',
      bandwidth: 10000,
      utilization: 52,
      status: 'active',
      type: 'ethernet',
      latency: 1.0,
      packetLoss: 0,
    },
    {
      id: 'link-leaf2-g2-1',
      source: 'leaf-2',
      target: 'group-2-1',
      bandwidth: 10000,
      utilization: 0,
      status: 'down',
      type: 'ethernet',
      latency: 999,
      packetLoss: 100,
    },
    {
      id: 'link-leaf2-g2-2',
      source: 'leaf-2',
      target: 'group-2-2',
      bandwidth: 10000,
      utilization: 0,
      status: 'down',
      type: 'ethernet',
      latency: 999,
      packetLoss: 100,
    },
    {
      id: 'link-leaf3-g3-1',
      source: 'leaf-3',
      target: 'group-3-1',
      bandwidth: 10000,
      utilization: 38,
      status: 'active',
      type: 'ethernet',
      latency: 1.0,
      packetLoss: 0,
    },
    {
      id: 'link-leaf3-g3-2',
      source: 'leaf-3',
      target: 'group-3-2',
      bandwidth: 10000,
      utilization: 42,
      status: 'active',
      type: 'ethernet',
      latency: 1.0,
      packetLoss: 0,
    },
    {
      id: 'link-leaf4-g4-1',
      source: 'leaf-4',
      target: 'group-4-1',
      bandwidth: 10000,
      utilization: 78,
      status: 'congested',
      type: 'ethernet',
      latency: 2.5,
      packetLoss: 0.1,
    },
    {
      id: 'link-leaf4-g4-2',
      source: 'leaf-4',
      target: 'group-4-2',
      bandwidth: 10000,
      utilization: 55,
      status: 'active',
      type: 'ethernet',
      latency: 1.2,
      packetLoss: 0,
    },
    {
      id: 'link-leaf5-g5-1',
      source: 'leaf-5',
      target: 'group-5-1',
      bandwidth: 10000,
      utilization: 35,
      status: 'active',
      type: 'ethernet',
      latency: 1.0,
      packetLoss: 0,
    },
    {
      id: 'link-leaf5-g5-2',
      source: 'leaf-5',
      target: 'group-5-2',
      bandwidth: 10000,
      utilization: 48,
      status: 'active',
      type: 'ethernet',
      latency: 1.0,
      packetLoss: 0,
    },
    {
      id: 'link-leaf6-g6-1',
      source: 'leaf-6',
      target: 'group-6-1',
      bandwidth: 10000,
      utilization: 32,
      status: 'active',
      type: 'ethernet',
      latency: 1.0,
      packetLoss: 0,
    },
    {
      id: 'link-leaf6-g6-2',
      source: 'leaf-6',
      target: 'group-6-2',
      bandwidth: 10000,
      utilization: 28,
      status: 'active',
      type: 'ethernet',
      latency: 1.0,
      packetLoss: 0,
    },
    // Group-Group 연결 (10G)
    {
      id: 'link-g1-1-g1-1-1',
      source: 'group-1-1',
      target: 'group-1-1-1',
      bandwidth: 10000,
      utilization: 22,
      status: 'active',
      type: 'ethernet',
      latency: 1.5,
      packetLoss: 0,
    },
    {
      id: 'link-g1-2-g1-2-1',
      source: 'group-1-2',
      target: 'group-1-2-1',
      bandwidth: 10000,
      utilization: 28,
      status: 'active',
      type: 'ethernet',
      latency: 1.5,
      packetLoss: 0,
    },
    {
      id: 'link-g2-1-g2-1-1',
      source: 'group-2-1',
      target: 'group-2-1-1',
      bandwidth: 10000,
      utilization: 0,
      status: 'down',
      type: 'ethernet',
      latency: 999,
      packetLoss: 100,
    },
    {
      id: 'link-g2-2-g2-2-1',
      source: 'group-2-2',
      target: 'group-2-2-1',
      bandwidth: 10000,
      utilization: 35,
      status: 'active',
      type: 'ethernet',
      latency: 1.5,
      packetLoss: 0,
    },
    {
      id: 'link-g3-1-g3-1-1',
      source: 'group-3-1',
      target: 'group-3-1-1',
      bandwidth: 10000,
      utilization: 18,
      status: 'active',
      type: 'ethernet',
      latency: 1.5,
      packetLoss: 0,
    },
    {
      id: 'link-g3-2-g3-2-1',
      source: 'group-3-2',
      target: 'group-3-2-1',
      bandwidth: 10000,
      utilization: 25,
      status: 'active',
      type: 'ethernet',
      latency: 1.5,
      packetLoss: 0,
    },
    {
      id: 'link-g4-1-g4-1-1',
      source: 'group-4-1',
      target: 'group-4-1-1',
      bandwidth: 10000,
      utilization: 65,
      status: 'active',
      type: 'ethernet',
      latency: 2.0,
      packetLoss: 0.02,
    },
    {
      id: 'link-g4-2-g4-2-1',
      source: 'group-4-2',
      target: 'group-4-2-1',
      bandwidth: 10000,
      utilization: 42,
      status: 'active',
      type: 'ethernet',
      latency: 1.5,
      packetLoss: 0,
    },
    {
      id: 'link-g5-1-g5-1-1',
      source: 'group-5-1',
      target: 'group-5-1-1',
      bandwidth: 10000,
      utilization: 20,
      status: 'active',
      type: 'ethernet',
      latency: 1.5,
      packetLoss: 0,
    },
    {
      id: 'link-g5-2-g5-2-1',
      source: 'group-5-2',
      target: 'group-5-2-1',
      bandwidth: 10000,
      utilization: 32,
      status: 'active',
      type: 'ethernet',
      latency: 1.5,
      packetLoss: 0,
    },
    {
      id: 'link-g6-1-g6-1-1',
      source: 'group-6-1',
      target: 'group-6-1-1',
      bandwidth: 10000,
      utilization: 15,
      status: 'active',
      type: 'ethernet',
      latency: 1.5,
      packetLoss: 0,
    },
    {
      id: 'link-g6-2-g6-2-1',
      source: 'group-6-2',
      target: 'group-6-2-1',
      bandwidth: 10000,
      utilization: 22,
      status: 'active',
      type: 'ethernet',
      latency: 1.5,
      packetLoss: 0,
    },
    // Leaf 간 VxLAN 터널 (크로스 연결)
    {
      id: 'link-leaf1-leaf3-vxlan',
      source: 'leaf-1',
      target: 'leaf-3',
      bandwidth: 10000,
      utilization: 25,
      status: 'active',
      type: 'vxlan', // VxLAN 터널
      isVxlanTunnel: true,
      vxlanVni: 5100,
      latency: 0.8,
      packetLoss: 0,
    },
    {
      id: 'link-leaf3-leaf4-vxlan',
      source: 'leaf-3',
      target: 'leaf-4',
      bandwidth: 10000,
      utilization: 30,
      status: 'active',
      type: 'vxlan', // VxLAN 터널
      isVxlanTunnel: true,
      vxlanVni: 5200,
      latency: 0.8,
      packetLoss: 0,
    },
  ];

  // VxLAN 터널 정의
  const vxlanTunnels: VxlanTunnel[] = [
    {
      id: 'vxlan-spine-1-2',
      vni: 5000,
      sourceVtep: '10.0.116.51',
      destVtep: '10.0.116.52',
      sourceNodeId: 'spine-1',
      destNodeId: 'spine-2',
      status: 'active',
      encapsulation: 'vxlan',
      mtu: 9000,
    },
    {
      id: 'vxlan-spine-2-3',
      vni: 5000,
      sourceVtep: '10.0.116.52',
      destVtep: '10.0.116.53',
      sourceNodeId: 'spine-2',
      destNodeId: 'spine-3',
      status: 'active',
      encapsulation: 'vxlan',
      mtu: 9000,
    },
    {
      id: 'vxlan-leaf-1-3',
      vni: 5100,
      sourceVtep: '10.0.116.61',
      destVtep: '10.0.116.52',
      sourceNodeId: 'leaf-1',
      destNodeId: 'leaf-3',
      status: 'active',
      encapsulation: 'vxlan',
      mtu: 9000,
    },
    {
      id: 'vxlan-leaf-3-4',
      vni: 5200,
      sourceVtep: '10.0.116.52',
      destVtep: '10.0.116.56',
      sourceNodeId: 'leaf-3',
      destNodeId: 'leaf-4',
      status: 'active',
      encapsulation: 'vxlan',
      mtu: 9000,
    },
  ];

  return { nodes, links, vxlanTunnels };
}

// 동적 데이터 업데이트 시뮬레이션
export function updateTopologyData(data: TopologyData): TopologyData {
  const updatedNodes = data.nodes.map(node => ({
    ...node,
    cpu: node.cpu ? Math.min(100, Math.max(0, node.cpu + (Math.random() - 0.5) * 10)) : undefined,
    memory: node.memory ? Math.min(100, Math.max(0, node.memory + (Math.random() - 0.5) * 10)) : undefined,
  }));

  const updatedLinks = data.links.map(link => {
    // Down 상태의 링크는 유지
    if (link.status === 'down') {
      return link;
    }

    const newUtilization = Math.min(100, Math.max(0, link.utilization + (Math.random() - 0.5) * 8));
    const newLatency = link.latency && link.latency < 999
      ? Math.max(0.1, link.latency + (Math.random() - 0.5) * 0.5)
      : link.latency;

    return {
      ...link,
      utilization: newUtilization,
      latency: newLatency,
      packetLoss: link.packetLoss !== undefined && link.packetLoss < 100
        ? Math.min(10, Math.max(0, link.packetLoss + (Math.random() - 0.5) * 0.1))
        : link.packetLoss,
      status: newUtilization > 75 ? 'congested' as const : 'active' as const,
    };
  });

  return {
    nodes: updatedNodes,
    links: updatedLinks,
    vxlanTunnels: data.vxlanTunnels, // VxLAN 터널은 그대로 유지
  };
}
